spring:
  datasource:
    hikari:
      driver-class-name: 'net.sf.log4jdbc.sql.jdbcapi.DriverSpy'
      jdbc-url: jdbc:log4jdbc:mysql://jdu.iptime.org:23306/apprentice?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: admin
      password: Thfk#930828

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

  mvc:
    hidden-method:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  # 메시지 관리 설정(오류메시지 등)
  messages:
    basename: messages, ValidationMessages, PropertyNames
    cache-duration: -1
    encoding: UTF-8
