spring:
  datasource:
    hikari:
      driver-class-name: 'net.sf.log4jdbc.sql.jdbcapi.DriverSpy'
      jdbc-url: jdbc:log4jdbc:mysql://50.18.231.176:3306/test?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: admin
      password: admin!@#

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      format_sql: true
      use_sql_comments: true
    open-in-view: false
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  # 로깅 설정
  logging:
    level:
      com:
        apprentice: DEBUG
      org:
        springframework: INFO
        thymeleaf: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

  # 메시지 관리 설정(오류메시지 등)
  messages:
    basename: messages, ValidationMessages, PropertyNames
    cache-duration: -1
    encoding: UTF-8